In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import os, json

In [2]:
hero_df = pd.read_csv("/Users/dell/Downloads/superhero_info - superhero_info.csv") 
hero_df

,Hero|Publisher,Gender,Race,Alignment,Hair color,Eye color,Skin color,Measurements
0,A-Bomb|Marvel Comics,Male,Human,good,No Hair,yellow,Unknown,"{'Height': '203.0 cm', 'Weight': '441.0 kg'}"
1,Abe Sapien|Dark Horse Comics,Male,Icthyo Sapien,good,No Hair,blue,blue,"{'Height': '191.0 cm', 'Weight': '65.0 kg'}"
2,Abin Sur|DC Comics,Male,Ungaran,good,No Hair,blue,red,"{'Height': '185.0 cm', 'Weight': '90.0 kg'}"
3,Abomination|Marvel Comics,Male,Human / Radiation,bad,No Hair,green,Unknown,"{'Height': '203.0 cm', 'Weight': '441.0 kg'}"
4,Absorbing Man|Marvel Comics,Male,Human,bad,No Hair,blue,Unknown,"{'Height': '193.0 cm', 'Weight': '122.0 kg'}"
...,...,...,...,...,...,...,...,...
458,Yellowjacket|Marvel Comics,Male,Human,good,Blond,blue,Unknown,"{'Height': '183.0 cm', 'Weight': '83.0 kg'}"
459,Yellowjacket II|Marvel Comics,Female,Human,good,Strawberry Blond,blue,Unknown,"{'Height': '165.0 cm', 'Weight': '52.0 kg'}"
460,Yoda|George Lucas,Male,Yoda's species,good,White,brown,green,"{'Height': '66.0 cm', 'Weight': '17.0 kg'}"
461,Zatanna|DC Comics,Female,Human,good,Black,blue,Unknown,"{'Height': '170.0 cm', 'Weight': '57.0 kg'}"
462,Zoom|DC Comics,Male,Unknown,bad,Brown,red,Unknown,"{'Height': '185.0 cm', 'Weight': '81.0 kg'}"

In [3]:
super_df = pd.read_csv("/Users/dell/Downloads/superhero_powers - superhero_powers.csv")
super_df

          hero_names                                             Powers
0            3-D Man         Agility,Super Strength,Stamina,Super Speed
1             A-Bomb  Accelerated Healing,Durability,Longevity,Super...
2         Abe Sapien  Agility,Accelerated Healing,Cold Resistance,Du...
3           Abin Sur                                 Lantern Power Ring
4        Abomination  Accelerated Healing,Intelligence,Super Strengt...
..               ...                                                ...
662  Yellowjacket II                 Flight,Energy Blasts,Size Changing
663             Ymir  Cold Resistance,Durability,Longevity,Super Str...
664             Yoda  Agility,Stealth,Danger Sense,Marksmanship,Weap...
665          Zatanna  Cryokinesis,Telepathy,Magic,Fire Control,Proba...
666             Zoom  Super Speed,Intangibility,Time Travel,Time Man...

[667 rows x 2 columns]

In [4]:
hero_df['Hero|Publisher']. str.split('|', expand = True)

                   0                  1
0             A-Bomb      Marvel Comics
1         Abe Sapien  Dark Horse Comics
2           Abin Sur          DC Comics
3        Abomination      Marvel Comics
4      Absorbing Man      Marvel Comics
..               ...                ...
458     Yellowjacket      Marvel Comics
459  Yellowjacket II      Marvel Comics
460             Yoda       George Lucas
461          Zatanna          DC Comics
462             Zoom          DC Comics

[463 rows x 2 columns]

In [5]:
hero_df[['Hero Name', 'Publisher']] = hero_df['Hero|Publisher']. str.split('|', expand = True)
hero_df.head()

,Hero|Publisher,Gender,Race,Alignment,Hair color,Eye color,Skin color,Measurements,Hero Name,Publisher
0,A-Bomb|Marvel Comics,Male,Human,good,No Hair,yellow,Unknown,"{'Height': '203.0 cm', 'Weight': '441.0 kg'}",A-Bomb,Marvel Comics
1,Abe Sapien|Dark Horse Comics,Male,Icthyo Sapien,good,No Hair,blue,blue,"{'Height': '191.0 cm', 'Weight': '65.0 kg'}",Abe Sapien,Dark Horse Comics
2,Abin Sur|DC Comics,Male,Ungaran,good,No Hair,blue,red,"{'Height': '185.0 cm', 'Weight': '90.0 kg'}",Abin Sur,DC Comics
3,Abomination|Marvel Comics,Male,Human / Radiation,bad,No Hair,green,Unknown,"{'Height': '203.0 cm', 'Weight': '441.0 kg'}",Abomination,Marvel Comics
4,Absorbing Man|Marvel Comics,Male,Human,bad,No Hair,blue,Unknown,"{'Height': '193.0 cm', 'Weight': '122.0 kg'}",Absorbing Man,Marvel Comics

In [6]:
hero_df = hero_df.drop(columns = ['Hero|Publisher'])
hero_df.head()

,Gender,Race,Alignment,Hair color,Eye color,Skin color,Measurements,Hero Name,Publisher
0,Male,Human,good,No Hair,yellow,Unknown,"{'Height': '203.0 cm', 'Weight': '441.0 kg'}",A-Bomb,Marvel Comics
1,Male,Icthyo Sapien,good,No Hair,blue,blue,"{'Height': '191.0 cm', 'Weight': '65.0 kg'}",Abe Sapien,Dark Horse Comics
2,Male,Ungaran,good,No Hair,blue,red,"{'Height': '185.0 cm', 'Weight': '90.0 kg'}",Abin Sur,DC Comics
3,Male,Human / Radiation,bad,No Hair,green,Unknown,"{'Height': '203.0 cm', 'Weight': '441.0 kg'}",Abomination,Marvel Comics
4,Male,Human,bad,No Hair,blue,Unknown,"{'Height': '193.0 cm', 'Weight': '122.0 kg'}",Absorbing Man,Marvel Comics

In [7]:
replace = ['{','}']
for char in replace:
    hero_df['Measurements']= hero_df['Measurements'].str.replace(char,'', regex = False)

In [8]:
hero_df.head()

,Gender,Race,Alignment,Hair color,Eye color,Skin color,Measurements,Hero Name,Publisher
0,Male,Human,good,No Hair,yellow,Unknown,"'Height': '203.0 cm', 'Weight': '441.0 kg'",A-Bomb,Marvel Comics
1,Male,Icthyo Sapien,good,No Hair,blue,blue,"'Height': '191.0 cm', 'Weight': '65.0 kg'",Abe Sapien,Dark Horse Comics
2,Male,Ungaran,good,No Hair,blue,red,"'Height': '185.0 cm', 'Weight': '90.0 kg'",Abin Sur,DC Comics
3,Male,Human / Radiation,bad,No Hair,green,Unknown,"'Height': '203.0 cm', 'Weight': '441.0 kg'",Abomination,Marvel Comics
4,Male,Human,bad,No Hair,blue,Unknown,"'Height': '193.0 cm', 'Weight': '122.0 kg'",Absorbing Man,Marvel Comics

In [9]:
height_weight = hero_df['Measurements'].apply(pd.Series)
height_weight

                                              0
0    'Height': '203.0 cm', 'Weight': '441.0 kg'
1     'Height': '191.0 cm', 'Weight': '65.0 kg'
2     'Height': '185.0 cm', 'Weight': '90.0 kg'
3    'Height': '203.0 cm', 'Weight': '441.0 kg'
4    'Height': '193.0 cm', 'Weight': '122.0 kg'
..                                          ...
458   'Height': '183.0 cm', 'Weight': '83.0 kg'
459   'Height': '165.0 cm', 'Weight': '52.0 kg'
460    'Height': '66.0 cm', 'Weight': '17.0 kg'
461   'Height': '170.0 cm', 'Weight': '57.0 kg'
462   'Height': '185.0 cm', 'Weight': '81.0 kg'

[463 rows x 1 columns]

In [10]:
hero_df[['Height','Weight']] = hero_df['Measurements'].str.split(',', expand = True)
hero_df.head()

,Gender,Race,Alignment,Hair color,Eye color,Skin color,Measurements,Hero Name,Publisher,Height,Weight
0,Male,Human,good,No Hair,yellow,Unknown,"'Height': '203.0 cm', 'Weight': '441.0 kg'",A-Bomb,Marvel Comics,'Height': '203.0 cm','Weight': '441.0 kg'
1,Male,Icthyo Sapien,good,No Hair,blue,blue,"'Height': '191.0 cm', 'Weight': '65.0 kg'",Abe Sapien,Dark Horse Comics,'Height': '191.0 cm','Weight': '65.0 kg'
2,Male,Ungaran,good,No Hair,blue,red,"'Height': '185.0 cm', 'Weight': '90.0 kg'",Abin Sur,DC Comics,'Height': '185.0 cm','Weight': '90.0 kg'
3,Male,Human / Radiation,bad,No Hair,green,Unknown,"'Height': '203.0 cm', 'Weight': '441.0 kg'",Abomination,Marvel Comics,'Height': '203.0 cm','Weight': '441.0 kg'
4,Male,Human,bad,No Hair,blue,Unknown,"'Height': '193.0 cm', 'Weight': '122.0 kg'",Absorbing Man,Marvel Comics,'Height': '193.0 cm','Weight': '122.0 kg'

In [11]:
hero_df = hero_df.drop(columns = ['Measurements'])
hero_df.head()

,Gender,Race,Alignment,Hair color,Eye color,Skin color,Hero Name,Publisher,Height,Weight
0,Male,Human,good,No Hair,yellow,Unknown,A-Bomb,Marvel Comics,'Height': '203.0 cm','Weight': '441.0 kg'
1,Male,Icthyo Sapien,good,No Hair,blue,blue,Abe Sapien,Dark Horse Comics,'Height': '191.0 cm','Weight': '65.0 kg'
2,Male,Ungaran,good,No Hair,blue,red,Abin Sur,DC Comics,'Height': '185.0 cm','Weight': '90.0 kg'
3,Male,Human / Radiation,bad,No Hair,green,Unknown,Abomination,Marvel Comics,'Height': '203.0 cm','Weight': '441.0 kg'
4,Male,Human,bad,No Hair,blue,Unknown,Absorbing Man,Marvel Comics,'Height': '193.0 cm','Weight': '122.0 kg'

In [12]:
hero_df['Height'] = hero_df['Height'].astype(str).str.replace("[']", "", regex=True)

In [13]:
hero_df['Weight'] = hero_df['Weight'].astype(str).str.replace("[']", "", regex=True)

In [14]:
replace = [' ']
for char in replace:
    hero_df['Height']= hero_df['Height'].str.replace(char,'', regex = False)

In [15]:
hero_df['Height'].head()

0    Height:203.0cm
1    Height:191.0cm
2    Height:185.0cm
3    Height:203.0cm
4    Height:193.0cm
Name: Height, dtype: object

In [16]:
hero_df['Height'] = hero_df['Height'].str[7:]
hero_df['Height']= hero_df['Height'].str.replace('cm','', regex = False)

In [20]:
hero_df['Height'] = hero_df['Height'].astype(float)
hero_df['Height']

0      203.0
1      191.0
2      185.0
3      203.0
4      193.0
       ...
458    183.0
459    165.0
460     66.0
461    170.0
462    185.0
Name: Height, Length: 463, dtype: float64

In [21]:
hero_df[['height1', 'Height(num)']] = hero_df['Height'].str.split(':', expand = True)
hero_df.head()

,Gender,Race,Alignment,Hair color,Eye color,Skin color,Hero Name,Publisher,Height,Weight,height1,Height(num)
0,Male,Human,good,No Hair,yellow,Unknown,A-Bomb,Marvel Comics,Height:203.0cm,Weight: 441.0 kg,Height,203.0cm
1,Male,Icthyo Sapien,good,No Hair,blue,blue,Abe Sapien,Dark Horse Comics,Height:191.0cm,Weight: 65.0 kg,Height,191.0cm
2,Male,Ungaran,good,No Hair,blue,red,Abin Sur,DC Comics,Height:185.0cm,Weight: 90.0 kg,Height,185.0cm
3,Male,Human / Radiation,bad,No Hair,green,Unknown,Abomination,Marvel Comics,Height:203.0cm,Weight: 441.0 kg,Height,203.0cm
4,Male,Human,bad,No Hair,blue,Unknown,Absorbing Man,Marvel Comics,Height:193.0cm,Weight: 122.0 kg,Height,193.0cm

In [22]:
hero_df = hero_df.drop(columns = ['height1', 'Height'])
hero_df.head()

,Gender,Race,Alignment,Hair color,Eye color,Skin color,Hero Name,Publisher,Weight,Height(num)
0,Male,Human,good,No Hair,yellow,Unknown,A-Bomb,Marvel Comics,Weight: 441.0 kg,203.0cm
1,Male,Icthyo Sapien,good,No Hair,blue,blue,Abe Sapien,Dark Horse Comics,Weight: 65.0 kg,191.0cm
2,Male,Ungaran,good,No Hair,blue,red,Abin Sur,DC Comics,Weight: 90.0 kg,185.0cm
3,Male,Human / Radiation,bad,No Hair,green,Unknown,Abomination,Marvel Comics,Weight: 441.0 kg,203.0cm
4,Male,Human,bad,No Hair,blue,Unknown,Absorbing Man,Marvel Comics,Weight: 122.0 kg,193.0cm

In [23]:
hero_df[['weight', 'Weight(num)']] = hero_df['Weight']. str.split(':', expand = True)
hero_df.head()

,Gender,Race,Alignment,Hair color,Eye color,Skin color,Hero Name,Publisher,Weight,Height(num),weight,Weight(num)
0,Male,Human,good,No Hair,yellow,Unknown,A-Bomb,Marvel Comics,Weight: 441.0 kg,203.0cm,Weight,441.0 kg
1,Male,Icthyo Sapien,good,No Hair,blue,blue,Abe Sapien,Dark Horse Comics,Weight: 65.0 kg,191.0cm,Weight,65.0 kg
2,Male,Ungaran,good,No Hair,blue,red,Abin Sur,DC Comics,Weight: 90.0 kg,185.0cm,Weight,90.0 kg
3,Male,Human / Radiation,bad,No Hair,green,Unknown,Abomination,Marvel Comics,Weight: 441.0 kg,203.0cm,Weight,441.0 kg
4,Male,Human,bad,No Hair,blue,Unknown,Absorbing Man,Marvel Comics,Weight: 122.0 kg,193.0cm,Weight,122.0 kg

In [24]:
hero_df = hero_df.drop(columns = ['weight', 'Weight'])
hero_df.head()

,Gender,Race,Alignment,Hair color,Eye color,Skin color,Hero Name,Publisher,Height(num),Weight(num)
0,Male,Human,good,No Hair,yellow,Unknown,A-Bomb,Marvel Comics,203.0cm,441.0 kg
1,Male,Icthyo Sapien,good,No Hair,blue,blue,Abe Sapien,Dark Horse Comics,191.0cm,65.0 kg
2,Male,Ungaran,good,No Hair,blue,red,Abin Sur,DC Comics,185.0cm,90.0 kg
3,Male,Human / Radiation,bad,No Hair,green,Unknown,Abomination,Marvel Comics,203.0cm,441.0 kg
4,Male,Human,bad,No Hair,blue,Unknown,Absorbing Man,Marvel Comics,193.0cm,122.0 kg

In [25]:
hero_df.head()

,Gender,Race,Alignment,Hair color,Eye color,Skin color,Hero Name,Publisher,Height(num),Weight(num)
0,Male,Human,good,No Hair,yellow,Unknown,A-Bomb,Marvel Comics,203.0cm,441.0 kg
1,Male,Icthyo Sapien,good,No Hair,blue,blue,Abe Sapien,Dark Horse Comics,191.0cm,65.0 kg
2,Male,Ungaran,good,No Hair,blue,red,Abin Sur,DC Comics,185.0cm,90.0 kg
3,Male,Human / Radiation,bad,No Hair,green,Unknown,Abomination,Marvel Comics,203.0cm,441.0 kg
4,Male,Human,bad,No Hair,blue,Unknown,Absorbing Man,Marvel Comics,193.0cm,122.0 kg

In [26]:
replace = [' ']
for char in replace:
    hero_df['Weight(num)']= hero_df['Weight(num)'].str.replace(char,'', regex = False)

In [27]:
hero_df['Weight(num)'].head()

0    441.0kg
1     65.0kg
2     90.0kg
3    441.0kg
4    122.0kg
Name: Weight(num), dtype: object

In [28]:
super_df.head()

    hero_names                                             Powers
0      3-D Man         Agility,Super Strength,Stamina,Super Speed
1       A-Bomb  Accelerated Healing,Durability,Longevity,Super...
2   Abe Sapien  Agility,Accelerated Healing,Cold Resistance,Du...
3     Abin Sur                                 Lantern Power Ring
4  Abomination  Accelerated Healing,Intelligence,Super Strengt...

In [29]:
super_df = super_df.drop(columns = ['hero_names'])
super_df.head()

                                              Powers
0         Agility,Super Strength,Stamina,Super Speed
1  Accelerated Healing,Durability,Longevity,Super...
2  Agility,Accelerated Healing,Cold Resistance,Du...
3                                 Lantern Power Ring
4  Accelerated Healing,Intelligence,Super Strengt...

In [23]:
exploded = exploded(super_df.assign(Powers = super_df.Powers.str.split(",")), 'Powers')

NameError: name 'exploded' is not defined

In [ ]:
super_df.explode('Powers')
super_df
#exploded[['Powers']].head()
#exploded =

In [22]:
super_df['Powers'] = super_df['Powers'].str.split(",")

NameError: name 'superhero_df' is not defined

In [ ]:
superhero_df.head()

In [ ]:
super_df['Powers'].value_counts

In [21]:
cols_to_make = exploded['Powers'].dropna().unique()
cols_to_make

NameError: name 'exploded' is not defined

In [ ]:
for col in cols_to_make:
    superhero_df[col] = superhero_df['Powers'].str.contains(col)
superhero_df.head()

In [ ]:
superhero_df

In [ ]:
#Sherlins code 
#df = pd.merge(hero_df, powers_df, left_on='Hero', right_on ='hero_names')

In [ ]:
superhero_df = pd.concat([hero_df, super_df], axis = 1, join = 'inner')
superhero_df.head()